### ISSUE TITLE
Element UI is not displayed on the inspector

### ISSUE THREAD

**Issue by saikrishna321** [mykola-mokhnach/Appium-iOS-Inspector#1]
![screen shot 2016-07-01 at 11 17 25 am](https://cloud.githubusercontent.com/assets/4045041/16512875/7b26236e-3f7d-11e6-8630-e05d4c9fe1b2.png)

**Comment by mykola-mokhnach** [comment]
Have you checked what is returned upon standard driver.getScreenshotAs() method call? Inspector just gets the screenshot image directly from Appium, which means we cannot get anything different from what Appium driver provides to us.

**Comment by saikrishna321** [comment]
@mykola-mokhnach i found the issue, when the simulator is resized to small(cmd+4) then it does not work. When i have the sim bugger it works fine.. 

driver.getScreenshotAs() also gets the blank screen when the sim is smaller.. closing the issue
