### ISSUE TITLE
Question: Increase Timeout?

### ISSUE THREAD

**Issue by Edge-Man** [mykola-mokhnach/Appium-iOS-Inspector#10]
Hi, This is a question but is it possible to increase the timeout? I'm seeing it crash when I try to pull the view I have a break point set and I'm assuming due to the elements in view it's taking awhile to process..

Thanks!

**Comment by Edge-Man** [comment]
And I think I found it! sorry for the premature post! 

in inspector.js...
const SCREENSHOT_GET_TIMEOUT_MS = 20000;
const SRC_XML_GET_TIMEOUT_MS = 60000;```

**Comment by jeangb** [comment]
Hello,
I've been editing these 2 constants and it doesn't change a thing.
I still have the "...source cannot be received after 10 seconds timeout. Click this ..." warning.
And the timeout is still the same.
Can you help me ?

**Comment by mykola-mokhnach** [comment]
@jeangb this timeout also depends on your Appium settings. But I would recommend trying [this WDA workaround](https://github.com/facebook/WebDriverAgent/issues/372) first unless your app source is really massive.

**Comment by jeangb** [comment]
@mykola-mokhnach Thank you for your answer. I use a desired capabilities to increase the timeout to.
I guess if I update appium to the latest version I'll have the workaround ?
Because I think my WDA is pretty recent so I may have already the workaround.

**Comment by mykola-mokhnach** [comment]
@jeangb yup, try 1.6.4-beta, where \@visible attribute has been excluded from xpath search. This might help.

**Comment by jeangb** [comment]
Hi @mykola-mokhnach I successfully installed appium1.6.4 but I still have the timeout problem on the appium ios inspector (on a certain page of the application). Do I have to do an other manipulation to make it work ?
Note that if I execute the GET request (from the appium server) in my browser I'll be able to get the json path.

**Comment by mykola-mokhnach** [comment]
@jeangb Try to play with timeouts in Appium settings

**Comment by jeangb** [comment]
Hey it works now, since I uncommented capabilities keychainPath and keychainPassword, I don't know if it's related.
Anyway, thanks !
