### ISSUE TITLE
Error after upgrading the Appium to 1.6.2.

### ISSUE THREAD

**Issue by ashfirebolt** [mykola-mokhnach/Appium-iOS-Inspector#13]
After I have upgraded the Appium to 1.6.2 I keep getting this error when I'm opening the iOS inspector. "

> Appium source at http://localhost:4723/wd/hub/bf439b9f-a7ce-4415-9fd5-0b5d071ea160/source cannot be received after 60 seconds timeout. Click this message to retry.

Thank you,

**Comment by mykola-mokhnach** [comment]
Please check https://github.com/facebook/WebDriverAgent/issues/372
