### ISSUE TITLE
Issues capturing view if it contains a high amount of complexity.

### ISSUE THREAD

**Issue by ericmeds** [mykola-mokhnach/Appium-iOS-Inspector#14]
I've noticed issues for views containing a high amount of buttons, images, tabs, etc (iPad apps). When attempting to capture this view, iOS Appium Inspector freezes up and does not return any results (browser ultimately asks to kill process). I am not sure where I can find logs but will gladly provide. Thank you!

**Comment by mykola-mokhnach** [comment]
Check the device logs while you are trying to load the structure into inspector. If you see something like 

```
Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessib
ilityElement: 0x61000024c510> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
```

then welcome to the [club](https://github.com/facebook/WebDriverAgent/issues/372).

It is known WDA/Apple issue and I cannot do anything about it. Inspector just tries to read and reflect what the underlying backend provides.

**Comment by ericmeds** [comment]
That is indeed the issue. :(
