### ISSUE TITLE
Bugfix for iOS Inspector (Compiling Issue)

### ISSUE THREAD

**Issue by gitjared** [mykola-mokhnach/Appium-iOS-Inspector#15]
Hi Could you implement this change in the Inspector.js code line 171?

Before:
for (var i=0; i < root.childNodes.length - 1; i++)

After:
for (var i=0; i < root.childNodes.length; i++)

![screen shot 2016-12-30 at 3 30 29 pm](https://cloud.githubusercontent.com/assets/8292026/21593169/1a5ec9fe-d0c9-11e6-834a-6182c5b93ff9

![screen shot 2016-12-30 at 1 46 14 pm](https://cloud.githubusercontent.com/assets/8292026/21593177/2b146394-d0c9-11e6-823d-8d8008b36970.png)
.png)

**Comment by mykola-mokhnach** [comment]
Thanks for the bugreport. Fixed
