### ISSUE TITLE
Appium 1.6.4-beta Issue

### ISSUE THREAD

**Issue by ericmeds** [mykola-mokhnach/Appium-iOS-Inspector#17]
Inspector no longer work in Appium 1.6.4-beta. No specific errors to speak of but it is unable to grab the element tree.

<img width="1223" alt="screen shot 2017-02-02 at 10 28 52 am" src="https://cloud.githubusercontent.com/assets/1964103/22555685/7db3b4b6-e932-11e6-90ac-3f9c265a0ecd.png">

**Comment by mykola-mokhnach** [comment]
Are you sure it is updated to the most recent commit? There was one small fix recently for a similar issue.

**Comment by ericmeds** [comment]
Looks like I didn't have the latest (thought I had pulled). Thank you!
