### ISSUE TITLE
syntax error, unexpected '<' <!DOCTYPE html>

### ISSUE THREAD

**Issue by puneetbohra** [mykola-mokhnach/Appium-iOS-Inspector#19]
While installing from **brew install https://github.com/mykola-mokhnach/Appium-iOS-Inspector** is giving error like : - syntax error, unexpected '<'
<!DOCTYPE html>
LOG DETAILS : - rror: Appium-iOS-Inspector: /Users/gopalprasad/Library/Caches/Homebrew/Formula/Appium-iOS-Inspector:7: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/Users/test/Library/Caches/Homebrew/Formula/Appium-iOS-Inspector:8: syntax error, unexpected '<'
<html lang="en">
 ^
/Users/test/Library/Caches/Homebrew/Formula/Appium-iOS-Inspector:9: syntax error, unexpected '<'
  <head>
   ^
/Users/test/Library/Caches/Homebrew/Formula/Appium-iOS-Inspector:14: syntax error, unexpected '<'
  <link crossorigin="anonymous" ...
   ^
/Users/test/Library/Caches/Homebrew/Formula/Appium-iOS-Inspector:14: syntax error, unexpected tIDENTIFIER, expecting end-of-input
...nk crossorigin="anonymous" href="https://assets-cdn.github.c...
...                               ^
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

Can anyone please help mw if i missed anything .

**Comment by mykola-mokhnach** [comment]
why brew? It will suffice to just clone the rep locally.

**Comment by puneetbohra** [comment]
Thanks @mykola-mokhnach  i have cloned it locally.
How to start the inspector or any specific command to inspector.
I have added screenshot for the same.
![screen shot 2017-02-27 at 12 41 11 pm](https://cloud.githubusercontent.com/assets/11886426/23351954/6e84524a-fcea-11e6-81a1-e8e4ef9e8ad0.png)

Appium is already started on default port : 4723

**Comment by mykola-mokhnach** [comment]
There's a README file. You need to put a breakpoint in your test code and only after that open this inspector.

**Comment by puneetbohra** [comment]
Thanks @mykola-mokhnach.
