### ISSUE TITLE
Question: Way to get the full AppiumAUT XML tree?

### ISSUE THREAD

**Issue by lambourn** [mykola-mokhnach/Appium-iOS-Inspector#2]
Is there a way to get the full XML tree of the current AppiumAUT object?

Reason is that I'd like to paste the XML tree into an editor so I can play around with the XPath (in addition to what's already in the inspector in terms of the XPath Helper)

The XML is loaded anyway so there should be an easy way to get a handle to it, right?

**Comment by mykola-mokhnach** [comment]
Unfortunately, there is no such possibility in the current build, but I can add it if needed

**Comment by lambourn** [comment]
that would be cool. I noticed that the raw XML gets stored in `Inspector.prototype.onTreeLoaded` on the Inspector object's `xml` property already so it could be grabbed from there.

**Comment by mykola-mokhnach** [comment]
@lambourn I have just added the "Copy XML To Clipboard" button and pushed the changes to master. Enjoy!

**Comment by lambourn** [comment]
Sweet!
