### ISSUE TITLE
http://localhost:4723 not working

### ISSUE THREAD

**Issue by sjenasears** [mykola-mokhnach/Appium-iOS-Inspector#20]
It is giving following error
The URL '/' did not map to a valid resource

**Comment by mykola-mokhnach** [comment]
Please provide the screenshot and the output of browser's javascript console

**Comment by sjenasears** [comment]
<img width="1378" alt="screen shot 2017-03-15 at 5 56 31 pm" src="https://cloud.githubusercontent.com/assets/25745554/23948692/2c475b3a-09aa-11e7-86f1-1241636d54c3.png">

**Comment by sjenasears** [comment]
<img width="1426" alt="screen shot 2017-03-15 at 6 15 45 pm" src="https://cloud.githubusercontent.com/assets/25745554/23949022/84a6fe06-09ab-11e7-9524-7499854f98fe.png">

**Comment by mykola-mokhnach** [comment]
This is not what is described in README. One has to start a test, wait until it is stopped on a breakpoint and only after that open "iOS Inspector.html" file in browser. In case you want to investigate an app without automated test running then you should try [Appium Desktop Beta](https://github.com/appium/appium-desktop/releases).
