### ISSUE TITLE
Unable to locate some mobile elements using appium inspector

### ISSUE THREAD

**Issue by BrainiacOfThemyscira** [mykola-mokhnach/Appium-iOS-Inspector#22]
Hello Appium gurus,
I am having some trouble locating some elements on our app(Native iOS App) . I want to ask if anybody encountered similar issue and what is the solution for this.
Attached a screenshot of the element i am trying to locate using appium inspector.

In the attached screenshot, i am able to locate the XCUIElementTypeCell , However appium inspector is unable to locate the static text present inside it.

Kindly help as i am stuck on this issue.

<img width="1079" alt="screen shot 2017-06-29 at 1 08 21 pm" src="https://user-images.githubusercontent.com/26822269/27709611-9dba3a06-5cd1-11e7-88b6-0b1205016a25.png">

**Comment by mykola-mokhnach** [comment]
Check https://github.com/appium/appium/issues/6517

Closed as non-inspector related issue.
