### ISSUE TITLE
Unable to close keyboard in iPad as the keyboard elements are displayed in portrait mode where it is actually in landscape mode[Refer SS]

### ISSUE THREAD

**Issue by Velladurai89** [mykola-mokhnach/Appium-iOS-Inspector#26]
Couldn't close the keyboard as the Hide Keyboard is not positioned properly. As you can see from the screnshots below the elements for keyboard alone is displaying in portrait mode. 

I don't know how to handle this. Could someone please help me solve this issue?

Appium Version: 1.6.4

![image](https://user-images.githubusercontent.com/24301002/31338621-aa9541b6-ad1d-11e7-86f3-a45aaeeb6f29.png)

![image](https://user-images.githubusercontent.com/24301002/31338674-dbade1b8-ad1d-11e7-96f0-5536a77c94b3.png)

![image](https://user-images.githubusercontent.com/24301002/31338702-ed55ccfa-ad1d-11e7-858b-5d64ce163b52.png)

**Comment by mykola-mokhnach** [comment]
This is known XCTest bug about landscape mode and the inspector just demonstrates it. However, there is a separate hideKeyboard API method in Appium. Try it.
