### ISSUE TITLE
Appium inspector timeout issue

### ISSUE THREAD

**Issue by rakeshsukla53** [mykola-mokhnach/Appium-iOS-Inspector#27]
# Problem

we recently updated:

- Xcode to 9.1 
- Appium to 1.7.1 
- iOS simulator to 11.0
- Device - Ipad Air 2 

and noticed the appium inspector timeout most of the time while loading the view.

<img width="1335" alt="screen shot 2017-10-25 at 12 24 18 pm" src="https://user-images.githubusercontent.com/9192661/32010349-947a67e4-b97f-11e7-9cd8-a6d66be4df1a.png">

We never encountered so much delay or timeout in the previous version:

- Xcode 8.3
- Appium 1.6.5 
- iOS simulator 10.3 
- Device - Ipad Air 2 

Is this a known issue ? Are you planning to push any changes ?

**Comment by mykola-mokhnach** [comment]
Yes this is [known](https://github.com/facebook/WebDriverAgent/issues/744) WDA issue. Apple did several changes in the recent iOS SDK and this made the stuff so slow
