### ISSUE TITLE
Accessibility Id: AX error -25205 displayed

### ISSUE THREAD

**Issue by rahulkulkarniyahoo** [mykola-mokhnach/Appium-iOS-Inspector#30]
Hello, After I came back from the winter vacation, i am see that I am getting the above mentioned error. 
Appium Verion:
Appium 1.6.5 and Appium 1.7
I have also tried Appium Desktop Version 1.2.4 and 1.2.7 using XCUITest. I get the same results. 
![ios appium inspector](https://user-images.githubusercontent.com/12827411/34674346-7bca49b0-f47d-11e7-8e24-09b41731fbec.png)

This was not happening before the December 22 nd when I last used it. 
I know this may not be related to Appium-iOS-Inspector, but I am unable to resolve it at the moment.

**Comment by mykola-mokhnach** [comment]
https://github.com/facebook/WebDriverAgent/issues/703
