### ISSUE TITLE
Appium session at http://localhost:4723/wd/hub is unreachable. Make sure your Appium test is running and click this message to retry.

### ISSUE THREAD

**Issue by pripriya2** [mykola-mokhnach/Appium-iOS-Inspector#38]
Hi, I am not able run appium ios inspector at all. I ends up throwing this error always:
Appium session at http://localhost:4723/wd/hub is unreachable. Make sure your Appium test is running and click this message to retry.

whereas when I enter http://localhost:4723/wd/hub/sessions in browser i am getting response.
Everything was wrking fine with Apium 1.8 after I upgraded to 1.12 facing this issue.
Appium 1.12
IOS 12.1

**Comment by mykola-mokhnach** [comment]
Do you see any errors in browser console?

**Comment by pripriya2** [comment]
Yes it was CORS error. i got it resolved with the workaround it is working fine. I will close the issue. I got this after upgrading to appium 1.12 so raised this.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
