### ISSUE TITLE
Can't load iOS INSPECTOR

### ISSUE THREAD

**Issue by lamquangthanh** [mykola-mokhnach/Appium-iOS-Inspector#39]
Hello,

I'm starting apps and appium successfully, but when open file Appium-iOS-Inspector.html , have and error with red "Appium session at https://localhost:4723/wd/hub is unreachable. Make sure..."

Have any change with way to start it?

Thanks

**Comment by ndeztea** [comment]
Hi,
I have the similiar issue after upgrade appium and xcode to the latest

thank you for the great job!

**Comment by mykola-mokhnach** [comment]
Check the network requests in the web inspector and browser console for possible error messages

**Comment by ndeztea** [comment]
It seems caused by CORS issue
```
Access to XMLHttpRequest at 'http://localhost:4725/wd/hub/sessions' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by mykola-mokhnach** [comment]
The workaround for CORS is described in README.

**Comment by ndeztea** [comment]
ok great, this is already solved this by installing CORS extensions on my browser

**Comment by lamquangthanh** [comment]
@ndeztea What's CORS extensions that you use?
