### ISSUE TITLE
Enhancement: add shortcut to reload

### ISSUE THREAD

**Issue by lambourn** [mykola-mokhnach/Appium-iOS-Inspector#4]
Would be sweet if there was an additional shortcut, e.g. the 'R' key to quickly reload the XML **and** the screenshot instead of hitting F5 to reload the full html.

**Comment by mykola-mokhnach** [comment]
Ctrl/Cmd + R usually does the job as well. I don't see any actual need in doing that

**Comment by lambourn** [comment]
yeah, you're right
