### ISSUE TITLE
Inspect element is not getting elemets and screen it showing broken image and null values.

### ISSUE THREAD

**Issue by sachin2788** [mykola-mokhnach/Appium-iOS-Inspector#5]
![screen shot 2016-10-20 at 6 26 06 pm](https://cloud.githubusercontent.com/assets/3167447/19560861/b96e8b98-96f3-11e6-910e-06e9c041efbd.png)
copy these file and run .html file in url, 
run the appium server and simulator after app launch no screen getting.

**Comment by mykola-mokhnach** [comment]
most likely there is an issue in Appium that we cannot properly get page source within the defined timeout. Please open javascript console and check the output there. It might be this happens because of this WDA issue: https://github.com/facebook/WebDriverAgent/pull/332
