### ISSUE TITLE
Navigation bar not being identified after opening a html page from iOS App

### ISSUE THREAD

**Issue by shivakrishnach31** [mykola-mokhnach/Appium-iOS-Inspector#7]
Hi,

From my App settings screen, clicking on 'show user guide' opens a html page in app itself with 'cancel' button on navigation bar. But after opening html guide I am unable to identify any of the element on the screen. Please see below screenshot and could you help me to identify elements on that screen.

![screen shot 2016-11-02 at 5 48 02 pm](https://cloud.githubusercontent.com/assets/8439309/19928498/b01fda7a-a124-11e6-88b3-df1c460b2b09.png)

**Comment by mykola-mokhnach** [comment]
It might be the same issue as in https://github.com/mykola-mokhnach/Appium-iOS-Inspector/issues/5

Please open the browser console and check the underlying error there to know more details
