### ISSUE TITLE
Improvements - Saving the screenshot and then reusing it as per the needs.

### ISSUE THREAD

**Issue by vishwathma** [mykola-mokhnach/Appium-iOS-Inspector#8]
I should be able to save a screenshot and then select and reuse it to check the element tree.xml as per need basis.

**Comment by mykola-mokhnach** [comment]
The page is static, which means you can just load it once and then use for elements location even if Appium service is not available anymore.
Regarding saving a screenshot - you can do it by simply saving it as picture or drag and drop it to your desktop. But it is not possible to restore inspector state only by having a single screenshot. The main requirement here is page source XML, which you cannot get without Appium service.
