### ISSUE TITLE
Unable to load inspector

### ISSUE THREAD

**Issue by pri1012** [mykola-mokhnach/Appium-iOS-Inspector#9]
Hi ,
I am trying to access the inspector.But getting the message Appium source could not be received afer 60 seconds.
Not sure what I am missing. Highly appreciate your help in this regard

**Comment by mykola-mokhnach** [comment]
This might happen due to [this](https://github.com/facebook/WebDriverAgent/issues/372) known WDA issue

**Comment by pri1012** [comment]
Thanks @mykola-mokhnach .Its working now
